#!/bin/bash

################################################################################
# Script: download-from-presigned-url.sh
# Description: Download a file from AWS S3 using a presigned URL
#              Requires NO AWS authentication
# Usage: ./download-from-presigned-url.sh <presigned-url> [destination-file]
################################################################################

set -e

# Colors for display
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Help function
show_help() {
    cat << EOF
Usage: ${0##*/} <presigned-url> [destination-file] [options]

Download a file from AWS S3 using a presigned URL.
No AWS authentication is required.

Arguments:
    presigned-url       S3 presigned URL generated by the administrator (required)
    destination-file    Path where to save the file (optional, default: filename extracted from URL)

Options:
    -v, --verbose       Verbose mode - displays more details
    -h, --help          Display this help

Examples:
    ${0##*/} "https://bucket.s3.amazonaws.com/..."
    ${0##*/} "https://bucket.s3.amazonaws.com/..." document.pdf
    ${0##*/} "https://bucket.s3.amazonaws.com/..." ./downloads/report.pdf --verbose

Notes:
    - The presigned URL must be valid (not expired)
    - Use quotes around the URL to avoid issues
    - The file will be downloaded to the current directory if no path is specified

EOF
}

# Function to display errors
print_error() {
    echo -e "${RED}❌ $1${NC}" >&2
}

# Function to display success
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

# Function to display warnings
print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

# Function to display info
print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Function to extract filename from URL
extract_filename_from_url() {
    local url="$1"

    # Extract the path part of the URL (before query parameters)
    local path="${url%%\?*}"

    # Extract the filename
    local filename=$(basename "$path")

    # If filename is empty or too short, use a default
    if [ -z "$filename" ] || [ "${#filename}" -lt 3 ]; then
        filename="downloaded-file-$(date +%Y%m%d-%H%M%S)"
    fi

    echo "$filename"
}

# Function to format size in readable format
format_size() {
    local bytes=$1

    if [ "$bytes" -lt 1024 ]; then
        echo "${bytes} B"
    elif [ "$bytes" -lt 1048576 ]; then
        echo "$(( bytes / 1024 )) KB"
    elif [ "$bytes" -lt 1073741824 ]; then
        echo "$(( bytes / 1048576 )) MB"
    else
        echo "$(( bytes / 1073741824 )) GB"
    fi
}

# Variables
VERBOSE=false
PRESIGNED_URL=""
OUTPUT_FILE=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -*)
            print_error "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            if [ -z "$PRESIGNED_URL" ]; then
                PRESIGNED_URL="$1"
            elif [ -z "$OUTPUT_FILE" ]; then
                OUTPUT_FILE="$1"
            else
                print_error "Too many arguments"
                show_help
                exit 1
            fi
            shift
            ;;
    esac
done

# Check required arguments
if [ -z "$PRESIGNED_URL" ]; then
    print_error "The presigned-url argument is required"
    echo ""
    show_help
    exit 1
fi

# Check if curl is installed
if ! command -v curl &> /dev/null; then
    print_error "curl is not installed"
    echo ""
    echo "Install curl with:"
    echo "  - Ubuntu/Debian: sudo apt-get install curl"
    echo "  - macOS: brew install curl"
    echo "  - CentOS/RHEL: sudo yum install curl"
    exit 1
fi

# Determine destination filename
if [ -z "$OUTPUT_FILE" ]; then
    OUTPUT_FILE=$(extract_filename_from_url "$PRESIGNED_URL")
    print_info "Detected filename: $OUTPUT_FILE"
fi

# Check if file already exists
if [ -f "$OUTPUT_FILE" ]; then
    print_warning "File '$OUTPUT_FILE' already exists"
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[OoYy]$ ]]; then
        print_info "Download cancelled"
        exit 0
    fi
fi

# Check if destination directory is writable
OUTPUT_DIR=$(dirname "$OUTPUT_FILE")
if [ ! -d "$OUTPUT_DIR" ]; then
    print_error "Directory '$OUTPUT_DIR' does not exist"
    exit 1
fi

if [ ! -w "$OUTPUT_DIR" ]; then
    print_error "Directory '$OUTPUT_DIR' is not writable"
    exit 1
fi

# Display information
echo ""
print_info "═══════════════════════════════════════════════════════════"
print_info "Download from S3 (via presigned URL)"
print_info "═══════════════════════════════════════════════════════════"
echo ""

if [ "$VERBOSE" = true ]; then
    echo "URL         : ${PRESIGNED_URL:0:80}..."
    echo "Destination : $OUTPUT_FILE"
    echo ""
fi

print_info "Retrieving file information..."
echo ""

# Get file information (Content-Length, Content-Type)
HEADER_INFO=$(curl -s -I "$PRESIGNED_URL" 2>&1)

if [ $? -ne 0 ]; then
    print_error "Unable to connect to server"
    echo ""
    echo "Possible causes:"
    echo "  • No internet connection"
    echo "  • The URL is incorrect"
    echo "  • Network issue"
    exit 1
fi

# Extract file size
CONTENT_LENGTH=$(echo "$HEADER_INFO" | grep -i "content-length:" | tail -1 | awk '{print $2}' | tr -d '\r')
CONTENT_TYPE=$(echo "$HEADER_INFO" | grep -i "content-type:" | tail -1 | cut -d' ' -f2- | tr -d '\r')

if [ -n "$CONTENT_LENGTH" ] && [ "$CONTENT_LENGTH" -gt 0 ]; then
    FILE_SIZE=$(format_size "$CONTENT_LENGTH")
    echo "Size        : $FILE_SIZE"
fi

if [ -n "$CONTENT_TYPE" ]; then
    echo "Type        : $CONTENT_TYPE"
fi

echo "Destination : $OUTPUT_FILE"
echo ""

print_info "Starting download..."
echo ""

# Prepare curl options
CURL_OPTS=(
    --location
    --output "$OUTPUT_FILE"
    --progress-bar
    -w "\n%{http_code}"
)

if [ "$VERBOSE" = true ]; then
    CURL_OPTS+=(--verbose)
else
    CURL_OPTS+=(--silent)
fi

# Perform download and capture HTTP code
HTTP_CODE=$(curl "${CURL_OPTS[@]}" "$PRESIGNED_URL" 2>&1 | tee /dev/stderr | tail -n1)

# Check result
echo ""
echo ""

case $HTTP_CODE in
    200)
        print_success "Download successful! (HTTP $HTTP_CODE)"
        echo ""

        # Display downloaded file size
        if [ -f "$OUTPUT_FILE" ]; then
            DOWNLOADED_SIZE=$(stat -f%z "$OUTPUT_FILE" 2>/dev/null || stat -c%s "$OUTPUT_FILE" 2>/dev/null)
            if [ -n "$DOWNLOADED_SIZE" ]; then
                DOWNLOADED_SIZE_FORMATTED=$(format_size "$DOWNLOADED_SIZE")
                print_info "The file has been saved to: $OUTPUT_FILE"
                print_info "Size: $DOWNLOADED_SIZE_FORMATTED"
            fi
        fi
        exit 0
        ;;
    403)
        # Remove partially downloaded file
        [ -f "$OUTPUT_FILE" ] && rm -f "$OUTPUT_FILE"

        print_error "Access denied (HTTP $HTTP_CODE)"
        echo ""
        echo "Possible causes:"
        echo "  • The presigned URL has expired"
        echo "  • The presigned URL is invalid"
        echo "  • S3 permissions are incorrect"
        echo ""
        echo "Solution: Request a new presigned URL from the administrator"
        exit 1
        ;;
    404)
        # Remove partially downloaded file
        [ -f "$OUTPUT_FILE" ] && rm -f "$OUTPUT_FILE"

        print_error "File not found (HTTP $HTTP_CODE)"
        echo ""
        echo "The file does not exist or has been removed from the S3 bucket"
        exit 1
        ;;
    400)
        # Remove partially downloaded file
        [ -f "$OUTPUT_FILE" ] && rm -f "$OUTPUT_FILE"

        print_error "Invalid request (HTTP $HTTP_CODE)"
        echo ""
        echo "The presigned URL is malformed"
        exit 1
        ;;
    000)
        # Remove partially downloaded file
        [ -f "$OUTPUT_FILE" ] && rm -f "$OUTPUT_FILE"

        print_error "Unable to connect to server"
        echo ""
        echo "Possible causes:"
        echo "  • No internet connection"
        echo "  • The URL is incorrect"
        echo "  • Network issue"
        exit 1
        ;;
    *)
        # Remove partially downloaded file
        [ -f "$OUTPUT_FILE" ] && rm -f "$OUTPUT_FILE"

        print_error "Download failed (HTTP $HTTP_CODE)"
        echo ""
        echo "An unexpected error occurred"
        echo "HTTP Code: $HTTP_CODE"
        exit 1
        ;;
esac
