#!/bin/bash

################################################################################
# Script: upload-to-presigned-url.sh
# Description: Upload a file to AWS S3 using a presigned URL
#              Requires NO AWS authentication
# Usage: ./upload-to-presigned-url.sh <file> <presigned-url>
################################################################################

set -e

# Colors for display
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Help function
show_help() {
    cat << EOF
Usage: ${0##*/} <file> <presigned-url> [options]

Upload a file to AWS S3 using a presigned URL.
No AWS authentication is required.

Arguments:
    file            Path to the file to upload (required)
    presigned-url   S3 presigned URL generated by the administrator (required)

Options:
    -v, --verbose   Verbose mode - displays more details
    -h, --help      Display this help

Examples:
    ${0##*/} document.pdf "https://bucket.s3.amazonaws.com/..."
    ${0##*/} photo.jpg "https://bucket.s3.amazonaws.com/..." --verbose

Notes:
    - The presigned URL must be valid (not expired)
    - The file will be uploaded as-is
    - Use quotes around the URL to avoid issues

EOF
}

# Function to display errors
print_error() {
    echo -e "${RED}❌ $1${NC}" >&2
}

# Function to display success
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

# Function to display warnings
print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

# Function to display info
print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Function to get file size in readable format
get_file_size() {
    local file="$1"
    local size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)

    if [ $? -ne 0 ]; then
        echo "unknown"
        return
    fi

    if [ "$size" -lt 1024 ]; then
        echo "${size} B"
    elif [ "$size" -lt 1048576 ]; then
        echo "$(( size / 1024 )) KB"
    elif [ "$size" -lt 1073741824 ]; then
        echo "$(( size / 1048576 )) MB"
    else
        echo "$(( size / 1073741824 )) GB"
    fi
}

# Function to detect MIME type
detect_mime_type() {
    local file="$1"

    # Try with 'file' command
    if command -v file &> /dev/null; then
        file -b --mime-type "$file" 2>/dev/null
    else
        # Fallback based on extension
        case "${file##*.}" in
            jpg|jpeg) echo "image/jpeg" ;;
            png) echo "image/png" ;;
            gif) echo "image/gif" ;;
            pdf) echo "application/pdf" ;;
            txt) echo "text/plain" ;;
            json) echo "application/json" ;;
            xml) echo "application/xml" ;;
            zip) echo "application/zip" ;;
            *) echo "application/octet-stream" ;;
        esac
    fi
}

# Variables
VERBOSE=false
FILE_PATH=""
PRESIGNED_URL=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -*)
            print_error "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            if [ -z "$FILE_PATH" ]; then
                FILE_PATH="$1"
            elif [ -z "$PRESIGNED_URL" ]; then
                PRESIGNED_URL="$1"
            else
                print_error "Too many arguments"
                show_help
                exit 1
            fi
            shift
            ;;
    esac
done

# Check required arguments
if [ -z "$FILE_PATH" ] || [ -z "$PRESIGNED_URL" ]; then
    print_error "File and presigned-url arguments are required"
    echo ""
    show_help
    exit 1
fi

# Check if curl is installed
if ! command -v curl &> /dev/null; then
    print_error "curl is not installed"
    echo ""
    echo "Install curl with:"
    echo "  - Ubuntu/Debian: sudo apt-get install curl"
    echo "  - macOS: brew install curl"
    echo "  - CentOS/RHEL: sudo yum install curl"
    exit 1
fi

# Check if file exists
if [ ! -f "$FILE_PATH" ]; then
    print_error "File '$FILE_PATH' does not exist"
    exit 1
fi

# Check if file is readable
if [ ! -r "$FILE_PATH" ]; then
    print_error "File '$FILE_PATH' is not readable"
    exit 1
fi

# Get file information
FILE_SIZE=$(get_file_size "$FILE_PATH")
FILE_MIME=$(detect_mime_type "$FILE_PATH")
FILE_NAME=$(basename "$FILE_PATH")

# Display information
echo ""
print_info "═══════════════════════════════════════════════════════════"
print_info "File upload to S3 (via presigned URL)"
print_info "═══════════════════════════════════════════════════════════"
echo ""
echo "File       : $FILE_NAME"
echo "Size       : $FILE_SIZE"
echo "MIME Type  : $FILE_MIME"
echo ""

if [ "$VERBOSE" = true ]; then
    echo "Full path  : $FILE_PATH"
    echo "URL        : ${PRESIGNED_URL:0:80}..."
    echo ""
fi

print_info "Starting upload..."
echo ""

# Prepare curl options
CURL_OPTS=(
    -X PUT
    -T "$FILE_PATH"
    -H "Content-Type: $FILE_MIME"
    --progress-bar
    -w "\n%{http_code}"
    -o /dev/null
)

if [ "$VERBOSE" = true ]; then
    CURL_OPTS+=(--verbose)
else
    CURL_OPTS+=(--silent)
fi

# Perform upload and capture HTTP code
HTTP_CODE=$(curl "${CURL_OPTS[@]}" "$PRESIGNED_URL" 2>&1 | tee /dev/stderr | tail -n1)

# Check result
echo ""
echo ""

case $HTTP_CODE in
    200)
        print_success "Upload successful! (HTTP $HTTP_CODE)"
        echo ""
        print_info "File '$FILE_NAME' was successfully uploaded to S3"
        exit 0
        ;;
    403)
        print_error "Access denied (HTTP $HTTP_CODE)"
        echo ""
        echo "Possible causes:"
        echo "  • The presigned URL has expired"
        echo "  • The presigned URL is invalid"
        echo "  • S3 permissions are incorrect"
        echo ""
        echo "Solution: Request a new presigned URL from the administrator"
        exit 1
        ;;
    400)
        print_error "Invalid request (HTTP $HTTP_CODE)"
        echo ""
        echo "Possible causes:"
        echo "  • The presigned URL is malformed"
        echo "  • The Content-Type does not match what was expected"
        echo ""
        exit 1
        ;;
    404)
        print_error "Bucket not found (HTTP $HTTP_CODE)"
        echo ""
        echo "The presigned URL points to a non-existent bucket"
        exit 1
        ;;
    000)
        print_error "Unable to connect to server"
        echo ""
        echo "Possible causes:"
        echo "  • No internet connection"
        echo "  • The URL is incorrect"
        echo "  • Network issue"
        exit 1
        ;;
    *)
        print_error "Upload failed (HTTP $HTTP_CODE)"
        echo ""
        echo "An unexpected error occurred"
        echo "HTTP Code: $HTTP_CODE"
        exit 1
        ;;
esac
